m_helpdesk_manage:
    lang: ACL_M_HELPDESK_MANAGE
    cat: misc

m_helpdesk_assign:
    lang: ACL_M_HELPDESK_ASSIGN
    cat: misc

m_helpdesk_bulk:
    lang: ACL_M_HELPDESK_BULK
    cat: misc

m_helpdesk_queue:
    lang: ACL_M_HELPDESK_QUEUE
    cat: misc
